version: "3"

services:
  database:
    container_name: self-service-app_database
    image: "postgres:14-alpine"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  webserver:
    container_name: self-service-app_webserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_HOST=database
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - MERCADOPAGO_ACCESS_TOKEN=${MERCADOPAGO_ACCESS_TOKEN}
      - ORDER_SERVICE_ENDPOINT=${ORDER_SERVICE_ENDPOINT}
      - RUN_ON=${RUN_ON}
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres-data:
